### ISSUE TITLE
Because it enables the session?

### ISSUE THREAD

**Issue by gustperz** [krisanalfa/lumen-dingo-adapter#1]
Because it enables the session?
I understand that an api is stateless, I do not have much experience and that is why I have the doubt.
I mean in what cases is it necessary?

**Comment by krisanalfa** [comment]
It still stateless. The session adapter is used by JWT for it's authentication. If you want to make sure, you can check that the session never stored in your server. Change session adapter to `file`, and check under your `storage/framework/sessions` folder, you'll find nothing.
